project:
  id: gcp-project-id
  region: europe-west1
  repository_name: pipelines # Artifact Registry repository name, where the pipeline YAML files are stored

  # The following fields are optional, here are the default values:

  # staging_bucket_suffix: pipeline-artifacts # The URI of the bucket will be: gs://<gcp-project-id>-<staging_bucket_suffix>
  # pipeline_service_account_name: vertex-pipelines # SA which used by the cloud function to run the pipelines
  # pipeline_service_account_roles: # Roles given to the pipeline runner service account (pipeline_service_account_name)
  #   - roles/editor
  # scheduler_service_account_name: vertex-scheduler # SA which used by the scheduler

scheduled_pipelines:
  hello_world_pipeline:
    cron_schedule: "*/20 * * * *"
    # time_zone: Europe/Paris # <-- optional, default: Europe/Paris
    enable_caching: false
    parameter_values:
      name: John Doe
  # pipeline-name-2: <-- add more pipelines by adding a pipeline name (inside the compiled pipeline YAML file, value of `pipelineInfo.name`)
  #   cron_schedule: "*/7 * * * *"
  #   enable_caching: false
  #   parameter_values:
  #     arg1: val1
  #     arg2: val2
